###   Create a new location
POST http://localhost:5000/api/itineraries/create
Content-Type: application/json

{
  "name": "Itin2"
}

###   Get all the locations
GET http://localhost:5000/api/itineraries

###   Get singular location (using ID)
GET http://localhost:5000/api/itineraries/1

###
DELETE  http://localhost:5000/api/itineraries/delete/cm8b2oibs0000wgu0m25ui2uj
